name: lint

on:
  pull_request:
    paths:
      - "**.js"
      - "**.ts"
      - "**.jsx"
      - "**.tsx"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: ESLint
        run: npm run lint
